/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherCoursesRouteImport } from './routes/_authenticated.teacher-courses'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated.submissions'
import { Route as AuthenticatedStudentCoursesRouteImport } from './routes/_authenticated.student-courses'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated.student'
import { Route as AuthenticatedReviewVerdictRouteImport } from './routes/_authenticated.review-verdict'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated.assignments'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedStudentCoursesIndexRouteImport } from './routes/_authenticated.student-courses.index'
import { Route as AuthenticatedAssignmentsIndexRouteImport } from './routes/_authenticated.assignments.index'
import { Route as AuthenticatedStudentCoursesAllRouteImport } from './routes/_authenticated.student-courses.all'
import { Route as AuthenticatedStudentCoursesCourseIdRouteImport } from './routes/_authenticated.student-courses.$courseId'
import { Route as AuthenticatedAssignmentsAssignmentIdRouteImport } from './routes/_authenticated.assignments.$assignmentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherCoursesRoute =
  AuthenticatedTeacherCoursesRouteImport.update({
    id: '/teacher-courses',
    path: '/teacher-courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentCoursesRoute =
  AuthenticatedStudentCoursesRouteImport.update({
    id: '/student-courses',
    path: '/student-courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewVerdictRoute =
  AuthenticatedReviewVerdictRouteImport.update({
    id: '/review-verdict',
    path: '/review-verdict',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentCoursesIndexRoute =
  AuthenticatedStudentCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentCoursesRoute,
  } as any)
const AuthenticatedAssignmentsIndexRoute =
  AuthenticatedAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssignmentsRoute,
  } as any)
const AuthenticatedStudentCoursesAllRoute =
  AuthenticatedStudentCoursesAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => AuthenticatedStudentCoursesRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdRoute =
  AuthenticatedStudentCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedStudentCoursesRoute,
  } as any)
const AuthenticatedAssignmentsAssignmentIdRoute =
  AuthenticatedAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => AuthenticatedAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/review-verdict': typeof AuthenticatedReviewVerdictRoute
  '/student': typeof AuthenticatedStudentRoute
  '/student-courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/teacher-courses': typeof AuthenticatedTeacherCoursesRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRoute
  '/student-courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/student-courses/all': typeof AuthenticatedStudentCoursesAllRoute
  '/assignments/': typeof AuthenticatedAssignmentsIndexRoute
  '/student-courses/': typeof AuthenticatedStudentCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/review-verdict': typeof AuthenticatedReviewVerdictRoute
  '/student': typeof AuthenticatedStudentRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/teacher-courses': typeof AuthenticatedTeacherCoursesRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRoute
  '/student-courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/student-courses/all': typeof AuthenticatedStudentCoursesAllRoute
  '/assignments': typeof AuthenticatedAssignmentsIndexRoute
  '/student-courses': typeof AuthenticatedStudentCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/_authenticated/review-verdict': typeof AuthenticatedReviewVerdictRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/student-courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/_authenticated/teacher-courses': typeof AuthenticatedTeacherCoursesRoute
  '/_authenticated/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRoute
  '/_authenticated/student-courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/_authenticated/student-courses/all': typeof AuthenticatedStudentCoursesAllRoute
  '/_authenticated/assignments/': typeof AuthenticatedAssignmentsIndexRoute
  '/_authenticated/student-courses/': typeof AuthenticatedStudentCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/assignments'
    | '/review-verdict'
    | '/student'
    | '/student-courses'
    | '/submissions'
    | '/teacher'
    | '/teacher-courses'
    | '/assignments/$assignmentId'
    | '/student-courses/$courseId'
    | '/student-courses/all'
    | '/assignments/'
    | '/student-courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/review-verdict'
    | '/student'
    | '/submissions'
    | '/teacher'
    | '/teacher-courses'
    | '/assignments/$assignmentId'
    | '/student-courses/$courseId'
    | '/student-courses/all'
    | '/assignments'
    | '/student-courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/assignments'
    | '/_authenticated/review-verdict'
    | '/_authenticated/student'
    | '/_authenticated/student-courses'
    | '/_authenticated/submissions'
    | '/_authenticated/teacher'
    | '/_authenticated/teacher-courses'
    | '/_authenticated/assignments/$assignmentId'
    | '/_authenticated/student-courses/$courseId'
    | '/_authenticated/student-courses/all'
    | '/_authenticated/assignments/'
    | '/_authenticated/student-courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher-courses': {
      id: '/_authenticated/teacher-courses'
      path: '/teacher-courses'
      fullPath: '/teacher-courses'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-courses': {
      id: '/_authenticated/student-courses'
      path: '/student-courses'
      fullPath: '/student-courses'
      preLoaderRoute: typeof AuthenticatedStudentCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review-verdict': {
      id: '/_authenticated/review-verdict'
      path: '/review-verdict'
      fullPath: '/review-verdict'
      preLoaderRoute: typeof AuthenticatedReviewVerdictRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-courses/': {
      id: '/_authenticated/student-courses/'
      path: '/'
      fullPath: '/student-courses/'
      preLoaderRoute: typeof AuthenticatedStudentCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesRoute
    }
    '/_authenticated/assignments/': {
      id: '/_authenticated/assignments/'
      path: '/'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AuthenticatedAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAssignmentsRoute
    }
    '/_authenticated/student-courses/all': {
      id: '/_authenticated/student-courses/all'
      path: '/all'
      fullPath: '/student-courses/all'
      preLoaderRoute: typeof AuthenticatedStudentCoursesAllRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesRoute
    }
    '/_authenticated/student-courses/$courseId': {
      id: '/_authenticated/student-courses/$courseId'
      path: '/$courseId'
      fullPath: '/student-courses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesRoute
    }
    '/_authenticated/assignments/$assignmentId': {
      id: '/_authenticated/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedAssignmentsRoute
    }
  }
}

interface AuthenticatedAssignmentsRouteChildren {
  AuthenticatedAssignmentsAssignmentIdRoute: typeof AuthenticatedAssignmentsAssignmentIdRoute
  AuthenticatedAssignmentsIndexRoute: typeof AuthenticatedAssignmentsIndexRoute
}

const AuthenticatedAssignmentsRouteChildren: AuthenticatedAssignmentsRouteChildren =
  {
    AuthenticatedAssignmentsAssignmentIdRoute:
      AuthenticatedAssignmentsAssignmentIdRoute,
    AuthenticatedAssignmentsIndexRoute: AuthenticatedAssignmentsIndexRoute,
  }

const AuthenticatedAssignmentsRouteWithChildren =
  AuthenticatedAssignmentsRoute._addFileChildren(
    AuthenticatedAssignmentsRouteChildren,
  )

interface AuthenticatedStudentCoursesRouteChildren {
  AuthenticatedStudentCoursesCourseIdRoute: typeof AuthenticatedStudentCoursesCourseIdRoute
  AuthenticatedStudentCoursesAllRoute: typeof AuthenticatedStudentCoursesAllRoute
  AuthenticatedStudentCoursesIndexRoute: typeof AuthenticatedStudentCoursesIndexRoute
}

const AuthenticatedStudentCoursesRouteChildren: AuthenticatedStudentCoursesRouteChildren =
  {
    AuthenticatedStudentCoursesCourseIdRoute:
      AuthenticatedStudentCoursesCourseIdRoute,
    AuthenticatedStudentCoursesAllRoute: AuthenticatedStudentCoursesAllRoute,
    AuthenticatedStudentCoursesIndexRoute:
      AuthenticatedStudentCoursesIndexRoute,
  }

const AuthenticatedStudentCoursesRouteWithChildren =
  AuthenticatedStudentCoursesRoute._addFileChildren(
    AuthenticatedStudentCoursesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRouteWithChildren
  AuthenticatedReviewVerdictRoute: typeof AuthenticatedReviewVerdictRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedStudentCoursesRoute: typeof AuthenticatedStudentCoursesRouteWithChildren
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedTeacherCoursesRoute: typeof AuthenticatedTeacherCoursesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRouteWithChildren,
  AuthenticatedReviewVerdictRoute: AuthenticatedReviewVerdictRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedStudentCoursesRoute:
    AuthenticatedStudentCoursesRouteWithChildren,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedTeacherCoursesRoute: AuthenticatedTeacherCoursesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
